name: Build

on: [push, pull_request]

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.2'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
